source 'https://rubygems.org'

ruby '2.4.0'
gem 'rails', '4.2.11'

group :development, :test do
  gem 'byebug'
  gem 'capybara', '2.4.4'
  gem 'database_cleaner', '1.4.1'
  gem 'factory_girl_rails'
  gem 'launchy'
  gem 'rspec-rails', '3.7.2'
  gem 'sqlite3'
  gem 'ZenTest', '4.11.0'
end

group :test do
  gem 'cucumber-rails', require: false
  gem 'cucumber-rails-training-wheels'
  gem 'simplecov', require: false
end

group :production do
  gem 'pg'
end

# Gems used only for assets and not required
# in production environments by default.

# gem 'therubyracer', '~> 0.12.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'sass-rails', '~> 5.0.3'
gem 'uglifier', '>= 2.7.1'

gem 'haml'
gem 'jquery-rails'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'
